// Research software, listed on the Research page. One line each, linking
// straight to the repository or documentation.

import type { Project } from "@/data/types";

export const projects: Project[] = [
  {
    id: "project-l4dc",
    name: "Switched-system identification",
    role: "Author",
    description:
      "Learning switching surfaces and vector fields from trajectory data through bilevel convex optimization, for the hybrid-system pipeline developed for L4DC 2026.",
    link: { label: "GitHub", href: "https://github.com/bernardorivas/L4DC-2026" },
  },
  {
    id: "project-latent-dynamics",
    name: "LatentDynamics",
    role: "Contributor",
    description: "Topological analysis of learned high-dimensional dynamics on low-dimensional latent spaces.",
    link: { label: "GitHub", href: "https://github.com/begelb/latent_dynamics" },
  },
  {
    id: "project-dsgrn",
    name: "DSGRN",
    role: "Contributor",
    description:
      "Dynamic Signatures Generated by Regulatory Networks produces database-scale dynamical surveys of switching models that can be queried for global behavior.",
    link: { label: "Documentation", href: "https://dsgrn.readthedocs.io/en/latest/" },
  },
  {
    id: "project-cmgdb",
    name: "CMGDB",
    role: "Contributor",
    description:
      "Conley–Morse Graph Database uses combinatorial and topological methods to compute global dynamics for discrete systems.",
    link: { label: "GitHub", href: "https://github.com/marciogameiro/CMGDB" },
  },
];
